name = "chromatic"
main = "src/worker.js"
compatibility_date = "2023-09-13"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[vars]
ALLOWED_ORIGINS =	["localhost", "preview-testnet-chromatic-protocol.netlify.app", "testnet.chromatic.finance"]
