name = "chromatic"
main = "src/worker.js"
compatibility_date = "2023-09-13"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[vars]
ALLOWED_ORIGINS =	'{ "0": "localhost", "1": "preview-testnet-chromatic-protocol.netlify.app", "2" : "testnet.chromatic.finance" }'